
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GestorContatos.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contato
{

    public Contato()
    {

        this.Telefones = new HashSet<Telefone>();

    }


    public int CodContato { get; set; }

    public string Nome { get; set; }

    public Nullable<System.DateTime> DataNascimento { get; set; }

    public string Email { get; set; }

    public string Endereco { get; set; }



    public virtual ICollection<Telefone> Telefones { get; set; }

}

}
